### ISSUE TITLE
Parse failure of `W//(m cdot K)`

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/asciimath2unitsml#27]
Failure in generating ISO Directives Part 2:
(https://github.com/metanorma/mn-samples-iso/pull/66)

https://github.com/metanorma/mn-samples-iso/runs/2378001857?check_suite_focus=true

```
[info]: Compiling /__w/mn-samples-iso/mn-samples-iso/sources/directives/part2/document.adoc ...
1753
/usr/local/bundle/gems/rsec-1.0.0/lib/rsec/parser.rb:19:in `parse!':  (Rsec::SyntaxError)
1754
in source:1 at 2
1755
W//(m cdot K)
1756
  ^
1757
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:114:in `parse'
1758
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:159:in `block in MathML2UnitsML'
1759
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
1760
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
1761
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
1762
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:156:in `MathML2UnitsML'
1763
	from /usr/local/bundle/gems/metanorma-standoc-1.9.0/lib/asciidoctor/standoc/cleanup_maths.rb:117:in `block in mathml_cleanup'
1764
```

**Comment by ronaldtse** [comment]
It worked after using the `symbol:` option to asciimath2unitsml:

```adoc
stem:[lambda = 220 xx (1 +- 0.02) "unitsml(W/(m*K), symbol: W//(m cdot K))"]
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/11865/115196936-0e40ff00-a123-11eb-8895-8553948e82bc.png">

Alternatively, this also works (already tried):
```adoc
stem:[lambda = 220 xx (1 +- 0.02) "unitsml(W/(m*K), multiplier: &#xb7;)"]
```
